name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run lint

      - name: e2e tests
        uses: cypress-io/github-action@59810ebfa5a5ac6fcfdcfdf036d1cd4d083a88f2 #(v.6.5.0)
        env:
          PORT: 3001
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
        if: ${{ !env.ACT }} # skipped when run using nektos/act since the default medium image does not contain xvfb which is required by cypress

      - name: Revision number
        id: revision
        run: echo "REVISION=$(cat config/common.js | grep '^const revision' | cut -d'=' -f 2 | cut -d';' -f 1)" >> $GITHUB_ENV

      - name: Initiate deployment
        id: init_deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
        if: ${{ github.event_name == 'push' && !env.ACT }}

      - name: Poll deployment success
        id: deploy_success
        uses: artiz/poll-endpoint@bebf08f9b9a25eda76824c4d0cae895cdee684aa # (v1.0.2)
        with:
          url: https://fullstackphonebook-joyj.onrender.com/api/revision
          method: GET
          expectStatus: 200
          expectBody: '${{ env.REVISION }}'
          timeout: 300000
          interval: 10000
        if: ${{ steps.init_deploy.outcome == 'success' }}
